# ===============================
# Netlify config for Decap CMS backend only
# ===============================

[build]
  # ⚠️ Không build Next.js tại đây
  publish = "public"
  command = "echo 'This site is only used for Decap CMS backend (Identity + Git Gateway)'"

# ✅ Cho phép xác thực từ domain Cloudflare Pages
[[redirects]]
  from = "https://wheeledit.com/*"
  to = "https://wheeledit.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://cms.wheeledit.com/*"
  to = "https://wheeledit.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://wheeledit.pages.dev/*"
  to = "https://wheeledit.netlify.app/:splat"
  status = 200
  force = true

# Security headers (optional)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
